language: rust
os:
    - linux
    - osx
rust:
    - stable
    - nightly
matrix:
    allow_failures:
        - rust: nightly
script:
    - cargo test
    - cargo test --no-default-features --features native-tls,blocking
    - cargo test --no-default-features --features rustls,blocking
    - cargo test --no-default-features --features native-tls,async
    - cargo test --no-default-features --features rustls,async

notifications:
    email: false
